### ISSUE TITLE
Expand on hover not working

### ISSUE THREAD

**Issue by nighto** [Eclipse1979/leaflet-slider#1]
Trying to use it on my project, the when I hover the 'S' icon, nothing happens. If I manually add `leaflet-control-slider-expanded` it works. Any idea why? Using current leaflet (0.7.3).

**Comment by Eclipse1979** [comment]
In leaflet-slider.js on line 94, try replacing :

```
L.DomEvent.on(this._container, {
                    mouseenter: this._expand,
                    mouseleave: this._collapse
                }, this);
```

by :

```
L.DomEvent
       .on(this._container, 'mouseenter', this._expand, this)
       .on(this._container, 'mouseleave', this._collapse, this);
```

Does this solve your issue ?
